
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import sun.net.www.http.HttpClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Focus
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelControl = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbMain = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        panelEvent = new javax.swing.JPanel();
        panelCreatelMember = new javax.swing.JPanel();
        btnAddCreate = new javax.swing.JButton();
        idTextFiled = new javax.swing.JTextField();
        IdLabel = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        SurnameTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        raceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelUpdateMember = new javax.swing.JPanel();
        btnAdd_Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFiled_Id_Update = new javax.swing.JTextField();
        txtFiled_Name_Update = new javax.swing.JTextField();
        txtFiled_Surname_Update = new javax.swing.JTextField();
        txtFiled_Race_Update = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelReadMember = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        readMemberIdtxtF = new javax.swing.JTextField();
        btnSearch_viewMember = new javax.swing.JButton();
        btnSearchAll_viewMember = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_viewMember = new javax.swing.JTextArea();
        paneldeleteMember = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtField_Id_DeletingMember = new javax.swing.JTextField();
        btnDeleteMember = new javax.swing.JButton();
        panelCreatelCoach = new javax.swing.JPanel();
        btnAddCreateCreCoach = new javax.swing.JButton();
        idTextFiled1CreCoach = new javax.swing.JTextField();
        IdLabel1 = new javax.swing.JLabel();
        nameTextfield1CreCoach = new javax.swing.JTextField();
        nameLabel1 = new javax.swing.JLabel();
        SurnameTextfieldCreCoach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        raceTextFieldCreCoach = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        panelUpdateCoach = new javax.swing.JPanel();
        btnAdd_UpdatCoach = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFiled_Id_UpdateCoach = new javax.swing.JTextField();
        txtFiled_Name_UpdateCoach = new javax.swing.JTextField();
        txtFiled_Surname_UpdateCoach = new javax.swing.JTextField();
        txtFiled_Race_UpdateCoach = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelReadCoach = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        readMemberIdtxtFCoach = new javax.swing.JTextField();
        btnSearch_Coach = new javax.swing.JButton();
        btnSearchAll_Coach = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea_Coach = new javax.swing.JTextArea();
        paneldeleteCoach = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtField_Id_DeletingCoach = new javax.swing.JTextField();
        btnDeleteCoach = new javax.swing.JButton();
        panelCreateTechnician = new javax.swing.JPanel();
        btnAddCreateTech = new javax.swing.JButton();
        idTextFiledTech = new javax.swing.JTextField();
        IdLabel2 = new javax.swing.JLabel();
        nameTextfieldTech = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        SurnameTextfieldTech = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        raceTextFieldTech = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        panelUpdateTechnician = new javax.swing.JPanel();
        btnAdd_UpdateTech = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtFiled_Id_UpdateTech = new javax.swing.JTextField();
        txtFiled_Name_UpdatTech = new javax.swing.JTextField();
        txtFiled_Surname_UpdateTech = new javax.swing.JTextField();
        txtFiled_Race_UpdateTech = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelReadTechnician = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        readMemberIdtxtFTech = new javax.swing.JTextField();
        btnSearch_viewMemberTech = new javax.swing.JButton();
        btnSearchAll_viewMemberTech = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea_viewTech = new javax.swing.JTextArea();
        paneldeleteTechnician = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtField_Id_DeletingTech = new javax.swing.JTextField();
        btnDeleteTech = new javax.swing.JButton();
        panelCreatelCleanners = new javax.swing.JPanel();
        btnAddCreateClnrs = new javax.swing.JButton();
        idTextFiledClnrs = new javax.swing.JTextField();
        IdLabel3 = new javax.swing.JLabel();
        nameTextfielClnrs = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        SurnameTextfieldClnrs = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        raceTextFielClnrs = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        panelUpdateCleanners = new javax.swing.JPanel();
        btnAdd_UpdateClnrs = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        Id_txtFiled_UpdatClnrs = new javax.swing.JTextField();
        txtFiled_Name_Updateclnrs = new javax.swing.JTextField();
        txtFiled_Surname_Update3 = new javax.swing.JTextField();
        txtFiled_Race_UpdateClnrs = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panelReadCleanners = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        readMemberIdtxtFClnrs = new javax.swing.JTextField();
        btnSearch_Clnrs = new javax.swing.JButton();
        btnSearchAll_Clnrs = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtArea_Clnrs = new javax.swing.JTextArea();
        paneldeleteCleanners = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txtField_Id_DeletingClnrs = new javax.swing.JTextField();
        btnDeleteClnrs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelControl.setBackground(new java.awt.Color(51, 0, 204));
        panelControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Menu"));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbMain.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Member", "Coach", "Technician", "Cleanner", " " }));
        cbMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMainActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("GYM HOSPITAL");

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(cbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEvent.setLayout(new java.awt.CardLayout());

        panelCreatelMember.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Member"));

        btnAddCreate.setText("Add");

        IdLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        IdLabel.setText("Id");

        nameTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameLabel.setText("Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Surname");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Race");

        javax.swing.GroupLayout panelCreatelMemberLayout = new javax.swing.GroupLayout(panelCreatelMember);
        panelCreatelMember.setLayout(panelCreatelMemberLayout);
        panelCreatelMemberLayout.setHorizontalGroup(
            panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelMemberLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(idTextFiled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(nameLabel)
                        .addComponent(SurnameTextfield)))
                .addGap(159, 159, 159))
            .addGroup(panelCreatelMemberLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnAddCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        panelCreatelMemberLayout.setVerticalGroup(
            panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelMemberLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelEvent.add(panelCreatelMember, "card2");

        panelUpdateMember.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Member"));

        btnAdd_Update.setText("Add");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Id");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Surname");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Race");

        javax.swing.GroupLayout panelUpdateMemberLayout = new javax.swing.GroupLayout(panelUpdateMember);
        panelUpdateMember.setLayout(panelUpdateMemberLayout);
        panelUpdateMemberLayout.setHorizontalGroup(
            panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateMemberLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateMemberLayout.createSequentialGroup()
                        .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtFiled_Id_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiled_Name_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(panelUpdateMemberLayout.createSequentialGroup()
                        .addComponent(txtFiled_Surname_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFiled_Race_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateMemberLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(127, 127, 127)))
                .addGap(157, 157, 157))
            .addGroup(panelUpdateMemberLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnAdd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateMemberLayout.setVerticalGroup(
            panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateMemberLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Id_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Name_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Surname_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Race_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnAdd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        panelEvent.add(panelUpdateMember, "card3");

        panelReadMember.setBorder(javax.swing.BorderFactory.createTitledBorder("View Member"));
        panelReadMember.setForeground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Member Id");

        btnSearch_viewMember.setText("Search..");
        btnSearch_viewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_viewMemberActionPerformed(evt);
            }
        });

        btnSearchAll_viewMember.setText("Search All ...");

        txtArea_viewMember.setColumns(20);
        txtArea_viewMember.setRows(5);
        jScrollPane2.setViewportView(txtArea_viewMember);

        javax.swing.GroupLayout panelReadMemberLayout = new javax.swing.GroupLayout(panelReadMember);
        panelReadMember.setLayout(panelReadMemberLayout);
        panelReadMemberLayout.setHorizontalGroup(
            panelReadMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadMemberLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelReadMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(panelReadMemberLayout.createSequentialGroup()
                        .addComponent(btnSearch_viewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchAll_viewMember))
                    .addComponent(readMemberIdtxtF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelReadMemberLayout.setVerticalGroup(
            panelReadMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadMemberLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readMemberIdtxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReadMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch_viewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAll_viewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(panelReadMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelEvent.add(panelReadMember, "card4");

        paneldeleteMember.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Member"));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Insert Id of the Member");

        btnDeleteMember.setText("Delete");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldeleteMemberLayout = new javax.swing.GroupLayout(paneldeleteMember);
        paneldeleteMember.setLayout(paneldeleteMemberLayout);
        paneldeleteMemberLayout.setHorizontalGroup(
            paneldeleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteMemberLayout.createSequentialGroup()
                .addGroup(paneldeleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldeleteMemberLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(paneldeleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtField_Id_DeletingMember, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneldeleteMemberLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        paneldeleteMemberLayout.setVerticalGroup(
            paneldeleteMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteMemberLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtField_Id_DeletingMember, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelEvent.add(paneldeleteMember, "card5");

        panelCreatelCoach.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Coach"));

        btnAddCreateCreCoach.setText("Add");

        IdLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        IdLabel1.setText("Id");

        nameTextfield1CreCoach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameLabel1.setText("Name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Surname");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Race");

        javax.swing.GroupLayout panelCreatelCoachLayout = new javax.swing.GroupLayout(panelCreatelCoach);
        panelCreatelCoach.setLayout(panelCreatelCoachLayout);
        panelCreatelCoachLayout.setHorizontalGroup(
            panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelCoachLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(IdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceTextFieldCreCoach, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(idTextFiled1CreCoach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameTextfield1CreCoach, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(nameLabel1)
                        .addComponent(SurnameTextfieldCreCoach)))
                .addGap(159, 159, 159))
            .addGroup(panelCreatelCoachLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnAddCreateCreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        panelCreatelCoachLayout.setVerticalGroup(
            panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelCoachLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel1)
                    .addComponent(nameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextFiled1CreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextfield1CreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raceTextFieldCreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameTextfieldCreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddCreateCreCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelEvent.add(panelCreatelCoach, "card2");

        panelUpdateCoach.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Coach"));

        btnAdd_UpdatCoach.setText("Add");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Id");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Name");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Surname");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Race");

        javax.swing.GroupLayout panelUpdateCoachLayout = new javax.swing.GroupLayout(panelUpdateCoach);
        panelUpdateCoach.setLayout(panelUpdateCoachLayout);
        panelUpdateCoachLayout.setHorizontalGroup(
            panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateCoachLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateCoachLayout.createSequentialGroup()
                        .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtFiled_Id_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiled_Name_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(panelUpdateCoachLayout.createSequentialGroup()
                        .addComponent(txtFiled_Surname_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFiled_Race_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateCoachLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(127, 127, 127)))
                .addGap(157, 157, 157))
            .addGroup(panelUpdateCoachLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnAdd_UpdatCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateCoachLayout.setVerticalGroup(
            panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateCoachLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Id_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Name_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Surname_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Race_UpdateCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnAdd_UpdatCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        panelEvent.add(panelUpdateCoach, "card3");

        panelReadCoach.setBorder(javax.swing.BorderFactory.createTitledBorder("View Coache"));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Member Id");

        btnSearch_Coach.setText("Search..");
        btnSearch_Coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_CoachActionPerformed(evt);
            }
        });

        btnSearchAll_Coach.setText("Search All ...");

        txtArea_Coach.setColumns(20);
        txtArea_Coach.setRows(5);
        jScrollPane3.setViewportView(txtArea_Coach);

        javax.swing.GroupLayout panelReadCoachLayout = new javax.swing.GroupLayout(panelReadCoach);
        panelReadCoach.setLayout(panelReadCoachLayout);
        panelReadCoachLayout.setHorizontalGroup(
            panelReadCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadCoachLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelReadCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addGroup(panelReadCoachLayout.createSequentialGroup()
                        .addComponent(btnSearch_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchAll_Coach))
                    .addComponent(readMemberIdtxtFCoach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelReadCoachLayout.setVerticalGroup(
            panelReadCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadCoachLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readMemberIdtxtFCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReadCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAll_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(panelReadCoachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelEvent.add(panelReadCoach, "card4");

        paneldeleteCoach.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Coach"));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Insert Id of the Member");

        btnDeleteCoach.setText("Delete");

        javax.swing.GroupLayout paneldeleteCoachLayout = new javax.swing.GroupLayout(paneldeleteCoach);
        paneldeleteCoach.setLayout(paneldeleteCoachLayout);
        paneldeleteCoachLayout.setHorizontalGroup(
            paneldeleteCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteCoachLayout.createSequentialGroup()
                .addGroup(paneldeleteCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldeleteCoachLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(paneldeleteCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtField_Id_DeletingCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneldeleteCoachLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnDeleteCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        paneldeleteCoachLayout.setVerticalGroup(
            paneldeleteCoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteCoachLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtField_Id_DeletingCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnDeleteCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelEvent.add(paneldeleteCoach, "card5");

        panelCreateTechnician.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Technician"));

        btnAddCreateTech.setText("Add");

        IdLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        IdLabel2.setText("Id");

        nameTextfieldTech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameLabel2.setText("Name");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Surname");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("Race");

        javax.swing.GroupLayout panelCreateTechnicianLayout = new javax.swing.GroupLayout(panelCreateTechnician);
        panelCreateTechnician.setLayout(panelCreateTechnicianLayout);
        panelCreateTechnicianLayout.setHorizontalGroup(
            panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateTechnicianLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addComponent(IdLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceTextFieldTech, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(idTextFiledTech))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameTextfieldTech, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(nameLabel2)
                        .addComponent(SurnameTextfieldTech)))
                .addGap(159, 159, 159))
            .addGroup(panelCreateTechnicianLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnAddCreateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        panelCreateTechnicianLayout.setVerticalGroup(
            panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateTechnicianLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel2)
                    .addComponent(nameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextFiledTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextfieldTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raceTextFieldTech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameTextfieldTech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddCreateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelEvent.add(panelCreateTechnician, "card2");

        panelUpdateTechnician.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Technician"));

        btnAdd_UpdateTech.setText("Add");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Id");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("Name");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setText("Surname");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("Race");

        javax.swing.GroupLayout panelUpdateTechnicianLayout = new javax.swing.GroupLayout(panelUpdateTechnician);
        panelUpdateTechnician.setLayout(panelUpdateTechnicianLayout);
        panelUpdateTechnicianLayout.setHorizontalGroup(
            panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateTechnicianLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateTechnicianLayout.createSequentialGroup()
                        .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtFiled_Id_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiled_Name_UpdatTech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(panelUpdateTechnicianLayout.createSequentialGroup()
                        .addComponent(txtFiled_Surname_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFiled_Race_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateTechnicianLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(127, 127, 127)))
                .addGap(157, 157, 157))
            .addGroup(panelUpdateTechnicianLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnAdd_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateTechnicianLayout.setVerticalGroup(
            panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateTechnicianLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Id_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Name_UpdatTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Surname_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Race_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnAdd_UpdateTech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        panelEvent.add(panelUpdateTechnician, "card3");

        panelReadTechnician.setBorder(javax.swing.BorderFactory.createTitledBorder("View Technician"));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setText("Member Id");

        btnSearch_viewMemberTech.setText("Search..");
        btnSearch_viewMemberTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_viewMemberTechActionPerformed(evt);
            }
        });

        btnSearchAll_viewMemberTech.setText("Search All ...");

        txtArea_viewTech.setColumns(20);
        txtArea_viewTech.setRows(5);
        jScrollPane4.setViewportView(txtArea_viewTech);

        javax.swing.GroupLayout panelReadTechnicianLayout = new javax.swing.GroupLayout(panelReadTechnician);
        panelReadTechnician.setLayout(panelReadTechnicianLayout);
        panelReadTechnicianLayout.setHorizontalGroup(
            panelReadTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadTechnicianLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelReadTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addGroup(panelReadTechnicianLayout.createSequentialGroup()
                        .addComponent(btnSearch_viewMemberTech, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchAll_viewMemberTech))
                    .addComponent(readMemberIdtxtFTech))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelReadTechnicianLayout.setVerticalGroup(
            panelReadTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadTechnicianLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readMemberIdtxtFTech, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReadTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch_viewMemberTech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAll_viewMemberTech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(panelReadTechnicianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelEvent.add(panelReadTechnician, "card4");

        paneldeleteTechnician.setBorder(javax.swing.BorderFactory.createTitledBorder("DeleteTechnician"));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("Insert Id of the Member");

        btnDeleteTech.setText("Delete");

        javax.swing.GroupLayout paneldeleteTechnicianLayout = new javax.swing.GroupLayout(paneldeleteTechnician);
        paneldeleteTechnician.setLayout(paneldeleteTechnicianLayout);
        paneldeleteTechnicianLayout.setHorizontalGroup(
            paneldeleteTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteTechnicianLayout.createSequentialGroup()
                .addGroup(paneldeleteTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldeleteTechnicianLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(paneldeleteTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtField_Id_DeletingTech, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneldeleteTechnicianLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnDeleteTech, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        paneldeleteTechnicianLayout.setVerticalGroup(
            paneldeleteTechnicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteTechnicianLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(txtField_Id_DeletingTech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnDeleteTech, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelEvent.add(paneldeleteTechnician, "card5");

        panelCreatelCleanners.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Cleanner"));

        btnAddCreateClnrs.setText("Add");

        IdLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        IdLabel3.setText("Id");

        nameTextfielClnrs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameLabel3.setText("Name");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setText("Surname");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText("Race");

        javax.swing.GroupLayout panelCreatelCleannersLayout = new javax.swing.GroupLayout(panelCreatelCleanners);
        panelCreatelCleanners.setLayout(panelCreatelCleannersLayout);
        panelCreatelCleannersLayout.setHorizontalGroup(
            panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelCleannersLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27)
                    .addComponent(IdLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceTextFielClnrs, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(idTextFiledClnrs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameTextfielClnrs, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(nameLabel3)
                        .addComponent(SurnameTextfieldClnrs)))
                .addGap(159, 159, 159))
            .addGroup(panelCreatelCleannersLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnAddCreateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        panelCreatelCleannersLayout.setVerticalGroup(
            panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreatelCleannersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel3)
                    .addComponent(nameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextFiledClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextfielClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreatelCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raceTextFielClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameTextfieldClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddCreateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelEvent.add(panelCreatelCleanners, "card2");

        panelUpdateCleanners.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Cleanner"));

        btnAdd_UpdateClnrs.setText("Add");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setText("Id");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setText("Name");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setText("Surname");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("Race");

        javax.swing.GroupLayout panelUpdateCleannersLayout = new javax.swing.GroupLayout(panelUpdateCleanners);
        panelUpdateCleanners.setLayout(panelUpdateCleannersLayout);
        panelUpdateCleannersLayout.setHorizontalGroup(
            panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateCleannersLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateCleannersLayout.createSequentialGroup()
                        .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(Id_txtFiled_UpdatClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiled_Name_Updateclnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(panelUpdateCleannersLayout.createSequentialGroup()
                        .addComponent(txtFiled_Surname_Update3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFiled_Race_UpdateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUpdateCleannersLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(127, 127, 127)))
                .addGap(157, 157, 157))
            .addGroup(panelUpdateCleannersLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnAdd_UpdateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUpdateCleannersLayout.setVerticalGroup(
            panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateCleannersLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_txtFiled_UpdatClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Name_Updateclnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiled_Surname_Update3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiled_Race_UpdateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnAdd_UpdateClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        panelEvent.add(panelUpdateCleanners, "card3");

        panelReadCleanners.setBorder(javax.swing.BorderFactory.createTitledBorder("View Cleanner"));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("Member Id");

        btnSearch_Clnrs.setText("Search..");
        btnSearch_Clnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_ClnrsActionPerformed(evt);
            }
        });

        btnSearchAll_Clnrs.setText("Search All ...");
        btnSearchAll_Clnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAll_ClnrsActionPerformed(evt);
            }
        });

        txtArea_Clnrs.setColumns(20);
        txtArea_Clnrs.setRows(5);
        jScrollPane5.setViewportView(txtArea_Clnrs);

        javax.swing.GroupLayout panelReadCleannersLayout = new javax.swing.GroupLayout(panelReadCleanners);
        panelReadCleanners.setLayout(panelReadCleannersLayout);
        panelReadCleannersLayout.setHorizontalGroup(
            panelReadCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadCleannersLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelReadCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32)
                    .addGroup(panelReadCleannersLayout.createSequentialGroup()
                        .addComponent(btnSearch_Clnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchAll_Clnrs))
                    .addComponent(readMemberIdtxtFClnrs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelReadCleannersLayout.setVerticalGroup(
            panelReadCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadCleannersLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readMemberIdtxtFClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReadCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch_Clnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAll_Clnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(panelReadCleannersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelEvent.add(panelReadCleanners, "card4");

        paneldeleteCleanners.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Cleanner"));
        paneldeleteCleanners.setForeground(new java.awt.Color(204, 204, 0));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setText("Insert Id of the Member");

        txtField_Id_DeletingClnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_Id_DeletingClnrsActionPerformed(evt);
            }
        });

        btnDeleteClnrs.setText("Delete");
        btnDeleteClnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClnrsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldeleteCleannersLayout = new javax.swing.GroupLayout(paneldeleteCleanners);
        paneldeleteCleanners.setLayout(paneldeleteCleannersLayout);
        paneldeleteCleannersLayout.setHorizontalGroup(
            paneldeleteCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteCleannersLayout.createSequentialGroup()
                .addGroup(paneldeleteCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldeleteCleannersLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(paneldeleteCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(txtField_Id_DeletingClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneldeleteCleannersLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnDeleteClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        paneldeleteCleannersLayout.setVerticalGroup(
            paneldeleteCleannersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeleteCleannersLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(txtField_Id_DeletingClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnDeleteClnrs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelEvent.add(paneldeleteCleanners, "card5");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       
        panelCreatelMember.setVisible(true);
        
        panelUpdateMember.setVisible(false);
        panelReadMember.setVisible(false); 
        paneldeleteMember.setVisible(false);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
       panelReadMember.setVisible(true); 
       
       panelCreatelMember.setVisible(false);
       panelUpdateMember.setVisible(false);
       paneldeleteMember.setVisible(false);
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        panelUpdateMember.setVisible(true);
        
        panelCreatelMember.setVisible(false);
        panelReadMember.setVisible(false);
        paneldeleteMember.setVisible(false);
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        paneldeleteMember.setVisible(true);
        
        panelCreatelMember.setVisible(false);
        panelReadMember.setVisible(false);
        panelUpdateMember.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearch_viewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_viewMemberActionPerformed
        // TODO add your handling code here:
        String url ="http://localhost:8080/member/read/"+readMemberIdtxtF.getText();
        
      try{
          
          CloseableHttpClient httpClient =HttpClients.createDefault();
          HttpGet getRequest = new HttpGet(url);
          getRequest.addHeader("accept", "application/json");
          
          HttpResponse response = httpClient.execute(getRequest);
          
          if(response.getStatusLine().getStatusCode() != 200){
                        throw new RuntimeException("Failed: HTTP error code: "
                        + response.getStatusLine().getStatusCode());
            }
           BufferedReader br = new BufferedReader(
                          new InputStreamReader((response.getEntity().getContent())));
           
           String output;
           System.out.println("Output from Server......\n");
           while((output = br.readLine()) != null) {
                 System.out.println(output);
                 txtArea_viewMember.append(output+"\n");
          }
        
      } catch (IOException | UnsupportedOperationException e){
                e.printStackTrace();
      }
       
    }//GEN-LAST:event_btnSearch_viewMemberActionPerformed

    private void btnSearch_CoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_CoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch_CoachActionPerformed

    private void btnSearch_viewMemberTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_viewMemberTechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch_viewMemberTechActionPerformed

    private void btnSearch_ClnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_ClnrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch_ClnrsActionPerformed

    private void cbMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMainActionPerformed
        // TODO add your handling code here:
         if(cbMain.getSelectedIndex()==0){
        panelReadMember.setVisible(true);
        
        
        
        panelUpdateMember.setVisible(false);
        panelReadMember.setVisible(false); 
        paneldeleteMember.setVisible(false);
        }else if(cbMain.getSelectedIndex()==1){
        panelReadCoach.setVisible(true);
            
        panelCreatelMember.setVisible(false);
        panelUpdateMember.setVisible(false);
        panelReadMember.setVisible(false); 
        paneldeleteMember.setVisible(false);
            
        } else if(cbMain.getSelectedIndex()==2){
        panelCreateTechnician.setVisible(true);
            
        
        panelReadCoach.setVisible(false);
        panelCreatelMember.setVisible(false);
        panelUpdateMember.setVisible(false);
        panelReadMember.setVisible(false); 
        paneldeleteMember.setVisible(false);
        } else if(cbMain.getSelectedIndex()==3){
        paneldeleteCleanners.setVisible(true);
         
        panelCreateTechnician.setVisible(false);
        panelReadCoach.setVisible(false);
        panelCreatelMember.setVisible(false);
        panelUpdateMember.setVisible(false);
        panelReadMember.setVisible(false); 
        paneldeleteMember.setVisible(false);  
        }
    }//GEN-LAST:event_cbMainActionPerformed

    private void btnSearchAll_ClnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAll_ClnrsActionPerformed
        // TODO add your handling code here:
         String url ="http://localhost:8080/member/all";
        
      try{
          
          CloseableHttpClient httpClient =HttpClients.createDefault();
          HttpGet getRequest = new HttpGet(url);
          getRequest.addHeader("accept", "application/json");
          
          HttpResponse response = httpClient.execute(getRequest);
          
          if(response.getStatusLine().getStatusCode() != 200){
                        throw new RuntimeException("Failed: HTTP error code: "
                        + response.getStatusLine().getStatusCode());
            }
           BufferedReader br = new BufferedReader(
                          new InputStreamReader((response.getEntity().getContent())));
           
          JOptionPane.showMessageDialog(null, "User was search succesfully");
      } catch (IOException | UnsupportedOperationException e){
                e.printStackTrace();
      }
    }//GEN-LAST:event_btnSearchAll_ClnrsActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        // TODO add your handling code here:
        String url ="http://localhost:8080/member/delete/"+txtField_Id_DeletingMember.getText();
        
      try{
          
          CloseableHttpClient httpClient =HttpClients.createDefault();
          HttpGet getRequest = new HttpGet(url);
          getRequest.addHeader("accept", "application/json");
          
          HttpResponse response = httpClient.execute(getRequest);
          
          if(response.getStatusLine().getStatusCode() != 200){
                        throw new RuntimeException("Failed: HTTP error code: "
                        + response.getStatusLine().getStatusCode());
            }
          //dele message
          JOptionPane.showMessageDialog(null, "The Member was delet succesfully");
           
        
      } catch (IOException | UnsupportedOperationException e){
                e.printStackTrace();
      }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void txtField_Id_DeletingClnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_Id_DeletingClnrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_Id_DeletingClnrsActionPerformed

    private void btnDeleteClnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClnrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteClnrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel IdLabel1;
    private javax.swing.JLabel IdLabel2;
    private javax.swing.JLabel IdLabel3;
    private javax.swing.JTextField Id_txtFiled_UpdatClnrs;
    private javax.swing.JTextField SurnameTextfield;
    private javax.swing.JTextField SurnameTextfieldClnrs;
    private javax.swing.JTextField SurnameTextfieldCreCoach;
    private javax.swing.JTextField SurnameTextfieldTech;
    private javax.swing.JButton btnAddCreate;
    private javax.swing.JButton btnAddCreateClnrs;
    private javax.swing.JButton btnAddCreateCreCoach;
    private javax.swing.JButton btnAddCreateTech;
    private javax.swing.JButton btnAdd_UpdatCoach;
    private javax.swing.JButton btnAdd_Update;
    private javax.swing.JButton btnAdd_UpdateClnrs;
    private javax.swing.JButton btnAdd_UpdateTech;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteClnrs;
    private javax.swing.JButton btnDeleteCoach;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnDeleteTech;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSearchAll_Clnrs;
    private javax.swing.JButton btnSearchAll_Coach;
    private javax.swing.JButton btnSearchAll_viewMember;
    private javax.swing.JButton btnSearchAll_viewMemberTech;
    private javax.swing.JButton btnSearch_Clnrs;
    private javax.swing.JButton btnSearch_Coach;
    private javax.swing.JButton btnSearch_viewMember;
    private javax.swing.JButton btnSearch_viewMemberTech;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbMain;
    private javax.swing.JTextField idTextFiled;
    private javax.swing.JTextField idTextFiled1CreCoach;
    private javax.swing.JTextField idTextFiledClnrs;
    private javax.swing.JTextField idTextFiledTech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JTextField nameTextfielClnrs;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JTextField nameTextfield1CreCoach;
    private javax.swing.JTextField nameTextfieldTech;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelCreateTechnician;
    private javax.swing.JPanel panelCreatelCleanners;
    private javax.swing.JPanel panelCreatelCoach;
    private javax.swing.JPanel panelCreatelMember;
    private javax.swing.JPanel panelEvent;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelReadCleanners;
    private javax.swing.JPanel panelReadCoach;
    private javax.swing.JPanel panelReadMember;
    private javax.swing.JPanel panelReadTechnician;
    private javax.swing.JPanel panelUpdateCleanners;
    private javax.swing.JPanel panelUpdateCoach;
    private javax.swing.JPanel panelUpdateMember;
    private javax.swing.JPanel panelUpdateTechnician;
    private javax.swing.JPanel paneldeleteCleanners;
    private javax.swing.JPanel paneldeleteCoach;
    private javax.swing.JPanel paneldeleteMember;
    private javax.swing.JPanel paneldeleteTechnician;
    private javax.swing.JTextField raceTextFielClnrs;
    private javax.swing.JTextField raceTextField;
    private javax.swing.JTextField raceTextFieldCreCoach;
    private javax.swing.JTextField raceTextFieldTech;
    private javax.swing.JTextField readMemberIdtxtF;
    private javax.swing.JTextField readMemberIdtxtFClnrs;
    private javax.swing.JTextField readMemberIdtxtFCoach;
    private javax.swing.JTextField readMemberIdtxtFTech;
    private javax.swing.JTextArea txtArea_Clnrs;
    private javax.swing.JTextArea txtArea_Coach;
    private javax.swing.JTextArea txtArea_viewMember;
    private javax.swing.JTextArea txtArea_viewTech;
    private javax.swing.JTextField txtField_Id_DeletingClnrs;
    private javax.swing.JTextField txtField_Id_DeletingCoach;
    private javax.swing.JTextField txtField_Id_DeletingMember;
    private javax.swing.JTextField txtField_Id_DeletingTech;
    private javax.swing.JTextField txtFiled_Id_Update;
    private javax.swing.JTextField txtFiled_Id_UpdateCoach;
    private javax.swing.JTextField txtFiled_Id_UpdateTech;
    private javax.swing.JTextField txtFiled_Name_UpdatTech;
    private javax.swing.JTextField txtFiled_Name_Update;
    private javax.swing.JTextField txtFiled_Name_UpdateCoach;
    private javax.swing.JTextField txtFiled_Name_Updateclnrs;
    private javax.swing.JTextField txtFiled_Race_Update;
    private javax.swing.JTextField txtFiled_Race_UpdateClnrs;
    private javax.swing.JTextField txtFiled_Race_UpdateCoach;
    private javax.swing.JTextField txtFiled_Race_UpdateTech;
    private javax.swing.JTextField txtFiled_Surname_Update;
    private javax.swing.JTextField txtFiled_Surname_Update3;
    private javax.swing.JTextField txtFiled_Surname_UpdateCoach;
    private javax.swing.JTextField txtFiled_Surname_UpdateTech;
    // End of variables declaration//GEN-END:variables
}
